- hosts: all
  become: yes
  tasks:
    # Install CUDA
    - name: Download installer
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_550.54.14_linux.run
        dest: /home/ubuntu/nfs/cuda/
        checksum: sha256:e6a842f4eca9490575cdb68b6b1bb78d47b95a897de48dee292c431892e57d17
        mode: 0550

    - name: Run the CUDA installer script with driver
      command: >
        sh /home/ubuntu/nfs/cuda/cuda_12.4.0_550.54.14_linux.run
        --silent
        --toolkit
        --samples
        --driver
      args:
        chdir: /home/ubuntu/nfs/cuda
        creates: /usr/local/cuda-12.4/version.txt
      environment:
        ACCEPT_EULA: "accept"
      register: cuda_install_output

    - name: Check CUDA installer output
      debug:
        var: cuda_install_output.stdout

    # Configure PATH for CUDA
    - name: Add CUDA to PATH system-wide
      lineinfile:
        path: /etc/profile.d/cuda.sh
        create: yes
        line: 'export PATH=/usr/local/cuda-12.4/bin${PATH:+:${PATH}}'
        state: present
        mode: '0644'

    - name: Add CUDA to PATH for user
      lineinfile:
        path: ~/.profile
        line: 'export PATH=/usr/local/cuda-12.4/bin${PATH:+:${PATH}}'
        state: present

    - name: Apply PATH changes for the current session
      shell: source ~/.profile
      args:
        executable: /bin/bash

    # Set CUDACXX Environment Variable
    - name: Set CUDACXX environment variable globally
      lineinfile:
        path: ~/.bashrc
        line: 'export CUDACXX=/usr/local/cuda-12.4/bin/nvcc'
        state: present

    - name: Apply CUDACXX changes for the current session
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

    # Start NVIDIA Persistence Daemon
    - name: Start NVIDIA Persistence Daemon
      command: /usr/bin/nvidia-persistenced --verbose
      register: persistenced_status

    - name: Display NVIDIA Persistence Daemon status
      debug:
        var: persistenced_status.stdout

    # GPU Direct Configuration
    - name: Load the `nvidia-peermem` kernel module
      modprobe:
        name: nvidia-peermem
        state: present

    - name: Ensure `nvidia-peermem` is loaded on boot
      lineinfile:
        path: /etc/modules
        line: "nvidia-peermem"
        state: present

    # Verify NVIDIA driver and CUDA installation
    - name: Check NVIDIA driver version
      command: cat /proc/driver/nvidia/version
      register: driver_version_output

    - name: Display NVIDIA driver version
      debug:
        var: driver_version_output.stdout

    - name: Check CUDA compiler version
      command: nvcc --version
      register: cuda_version_output
      failed_when: "'not found' in cuda_version_output.stdout"

    - name: Display CUDA compiler version
      debug:
        var: cuda_version_output.stdout

    - name: Check NVIDIA GPU status
      command: nvidia-smi
      register: nvidia_smi_output
      failed_when: "'not found' in nvidia_smi_output.stdout"

    - name: Display NVIDIA GPU status
      debug:
        var: nvidia_smi_output.stdout
