- name: Provisioning ubuntu
  hosts: all
  tasks:
   - name: Create a user 'ubuntu' with a home directory
     become: true
     ansible.builtin.user:
       name: ubuntu
       create_home: yes

   - name: Install runtime prerrequsites
     become: true
     ansible.builtin.apt:
       name:
         - git
         - openssl
         - gcc
       state: present
       update_cache: yes

   - name: Remove the repo
     become: true
     file:
       state: absent
       path: /home/ubuntu/health_interoperability_AI

   - name: Clone snomed repo master branch
     ansible.builtin.git:
       repo:  https://github.com/richhl/health_interoperability_AI.git
       dest: /home/ubuntu/health_interoperability_AI
       version: main
       accept_hostkey: yes

   - name: Install Conda
     block:
       - name: Download Miniconda
         get_url:
           url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
           dest: /tmp/install-miniconda.sh
           checksum: sha256:4766d85b5f7d235ce250e998ebb5a8a8210cbd4f2b0fea4d2177b3ed9ea87884
           mode: 0550
       - name: Create conda folder
         become: True
         file:
           path: /opt/miniconda3
           state: directory
           owner: ubuntu
           mode: 755
           recurse: yes
       - name: Run the installer
         become: true
         shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
       - name: Remove the installer
         file:
           state: absent
           path: /tmp/install-miniconda.sh
       - name: Add miniconda bin to path
         become: True
         shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile
       - name: conda - read permission for all
         become: True
         file:
           path: /opt/miniconda3
           mode: +r
           recurse: yes
       - name: conda - execution permission for all
         become: True
         file:
           path: /opt/miniconda3/bin
           mode: +x
           recurse: yes


#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.file:
#       path: "/home/ubuntu/health_interoperability_AI/data"
#       state: "directory"

#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.copy:
#       src: "/home/christian/grado/tfg/health_interoperability_AI/data/mimic-iv_notes_training_set.csv"
#       dest: "/home/ubuntu/health_interoperability_AI/data"

#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.file:
#       path: "/home/ubuntu/health_interoperability_AI/assets"
#       state: "directory"

#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.copy:
#       src: "/home/christian/grado/tfg/health_interoperability_AI/assets/train_annotations.csv"
#       dest: "/home/ubuntu/health_interoperability_AI/assets"

#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.file:
#       path: "/home/ubuntu/health_interoperability_AI/backup"
#       state: "directory"

#   - name: Copy premade files
#     become_user: ubuntu
#     become: true
#     ansible.builtin.copy:
#       src: "/home/christian/grado/tfg/health_interoperability_AI/backup/annotations_extended_for_classification.gzip"
#       dest: "/home/ubuntu/health_interoperability_AI/backup"

   - name: Use faisscpu for my environment
     ansible.builtin.lineinfile:
       path: "/home/ubuntu/health_interoperability_AI/requirements_snomed_{{ purpose | default('training')}}.yml"
       regexp: '      - faiss-gpu==1.7.4'
       line: '      - faiss-cpu==1.7.4'

   - name: Create snomed environment
     become_user: ubuntu
     shell: source /opt/miniconda3/etc/profile.d/conda.sh && cd "/home/ubuntu/health_interoperability_AI" && conda env create -f "requirements_snomed_{{ purpose | default('training')}}.yml"
     args:
       executable: /bin/bash
       creates: /home/ubuntu/.conda/envs/snomedct

   - name: Activate snomed && logging huggingface
     become_user: ubuntu
     shell: source /opt/miniconda3/etc/profile.d/conda.sh && conda activate snomedct && pip install --upgrade huggingface_hub && huggingface-cli login --token {{ lookup('ansible.builtin.env', 'MY_HF_TOKEN') }}
     args:
       executable: /bin/bash

#   - name: Not fast tokenizer to avoid bug
#     ansible.builtin.lineinfile:
#       path: "/home/ubuntu/health_interoperability_AI/Finetuning-Entity-Recognition.py"
#       regexp: '^tokenizer ='
#       line: 'tokenizer = transformers.AutoTokenizer.from_pretrained(model_id, use_fast=False)'
